name: poll_answer
description: Приложение для создания опрос с целью получения мнения большинства. Минимальная версия поддерживаемого android 5 (SDK 21)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # визуал
  flutter_neumorphic: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  material_floating_search_bar: ^0.3.6
  animate_do: ^2.0.0
  lottie: ^1.2.1
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  
  # DI, навигация, MVC
  get: ^4.6.1

  # сеть 
  http: ^0.13.4
  
  # графики
  fl_chart: ^0.40.6

  # кэширование
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  
  # шрифты
  google_fonts: ^2.1.1

  # разрешения
  permission_handler: ^8.3.0
  
  # пуши 
  awesome_notifications: ^0.6.19

  # локализация
  easy_localization: ^3.0.0

  # аналитика
  firebase_crashlytics: ^2.4.4

  # загрузка картинок
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
      - assets/translations/
      - assets/img/ic_profile.png
      - assets/img/ic_profile_selected.png
      - assets/img/ic_task.png
      - assets/img/ic_add_quiz.png
      - assets/img/ic_add_quiz_selected.png
      - assets/img/ic_task_selected.png
      - assets/img/no_connect.png
      - assets/img/ic_map.png
      - assets/img/ic_edit.png
      - assets/img/ic_map_en.png
      - assets/img/plug_image.png
      - assets/anim/loader.json

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik_regular.ttf
          weight: 400
    - family: exo
      fonts:
        - asset: assets/fonts/exo.ttf
          weight: 400 